<label><?php echo e(__('messages.Currency')); ?></label><span class="text-danger">*</span>  
<div class="form-group">
    <div class="form-row">
        <div class="col">
            <?php
                /*
                <select  class="form-control" name="currency" required>
                <option selected value="">Select currency</option>
                <option value="{{ $sitesettings->currencySymbol }} - {{ $sitesettings->currencyCode }}" selected>{{ $sitesettings->currencySymbol }} - {{ $sitesettings->currencyCode }}</option>
                <option value="£ - GBP">United Kingdom Pounds – GBP</option>
                <option value="$ - USD">America (United States) Dollars – USD</option>
                <option value="¥ - JPY">Japan Yen – JPY</option>
                <option value="$ - AUD">Australia Dollars – AUD</option>
                <option value="R$ - BRL">Brazil Reais – BRL</option>
                <!-- <option value="лв - BGN">Bulgaria Leva – BGN</option> -->
                <option value="$ - CAD">Canada Dollars – CAD</option>
                <!-- <option value="$ - CLP">Chile Pesos – CLP</option> -->
                <option value="€ - EUR">Euro – EUR</option>
                <!-- <option value="¥ /元 - CNY">China Yuan Renminbi – CNY</option> -->
                <option value="Kč - CZK">Czech Republic Koruny – CZK</option>
                <option value="kr - DKK">Denmark Kroner – DKK</option>
                <!-- <option value="$ - COP">Colombia Pesos – COP</option> -->
                <option value="$ - USD">United States Dollars – USD</option>
                <!-- <option value="৳ - BDT">Bangladesh Taka – BDT</option> -->
                <!-- <option value="₹ - INR">India Rupees – INR</option> -->
               <!--  <option value="Rp - IDR">Indonesia Rupiahs – IDR</option> -->
                <option value="ft - HUF">Hungary Forint – HUF</option>
                <option value="$ - HKD ">Hong Kong Dollars – HKD</option>
                <option value="₪ - ILS">Israel New Shekels – ILS</option>
                <option value="$ - MXN">Mexico Pesos – MXN</option>
                <!-- <option value="د.م - MAD">Morocco Dirhams – MAD</option> -->
                <option value="RM - MYR">Malaysia Ringgits – MYR</option>
                <option value="$ - NZD">New Zealand Dollars – NZD</option>
                <option value="kr - NOK">Norway Kroner – NOK</option>
                <!-- <option value="S/. - PEN">Peru Nuevos Soles – PEN</option> -->
                <option value="₱ - PHP">Philippines Pesos – PHP</option>
                <!-- <option value="Rs - PKR">Pakistan Rupees – PKR</option> -->
                <option value="zł - PLN">Poland Zlotych – PLN</option>
                <option value="₽ - RUB">Russia Rubles – RUB</option>
                <option value="$ - SGD">Singapore Dollars – SGD</option>
                <!-- <option value="R - ZAR">South Africa Rand – ZAR</option> -->
                <!-- <option value="₩ - KRW">South Korea Won – KRW</option> -->
                <!-- <option value="kn - HRK">Croatia Kuna – HRK</option> -->
                <!-- <option value="Rs - LKR">Sri Lanka Rupees – LKR</option> -->
                <option value="kr - SEK">Sweden Kronor – SEK</option>
                <option value="CHF - CHF">Switzerland Francs – CHF</option>
                <option value= "฿  - THB">Thailand Baht – THB</option>
                <option value="₺ - TRY">Turkey New Lira – TRY</option>
               <!--  <option value="د.إ - AED">United Arab Emirates Dirhams – AED</option> -->
                <!-- <option value="₫ - VND">Vietnam Dong – VND</option> -->
                <!-- <option value="B$ - BSD">Bahamas Dollars – BSD</option> -->
                <!-- <option value="$ - ARS">Argentina Pesos – ARS</option> -->
                <!-- <option value="$ - DOP">Dominican Republic Pesos – DOP</option> -->
                <!-- <option value="FRF - FRF*">France Francs – FRF*</OPTION> -->
                <!-- <option value="öS - ATS">Austria Schillings – ATS</OPTION> -->
                <!-- <option value="fr - BEF">Belgium Francs – BEF</OPTION> -->
                <!-- <option value="₡ - CRC">Costa Rica Colones – CRC</option> -->
                <!-- <option value="Afghanistan Afghanis - AFN">Afghanistan Afghanis – AFN</option> -->
                <!-- <option value="Albania Leke - ALL">Albania Leke – ALL</option> -->
                <!-- <option value="Algeria Dinars - DZD">Algeria Dinars – DZD</option> -->
                <!-- <option value="Bahrain Dinars - BHD">Bahrain Dinars – BHD</option> -->
                <!-- <option value="Barbados Dollars - BBD">Barbados Dollars – BBD</option> -->
                <!-- <option value="Bermuda Dollars - BMD">Bermuda Dollars – BMD</option> -->
               <!--  <option value="CFA - XOF">CFA BCEAO Francs – XOF</option>
                <option value="CFA - XAF">CFA BEAC Francs – XAF</option> -->
                <!-- <option value="RMB (China Yuan Renminbi) - CNY">RMB (China Yuan Renminbi) – CNY</option>
                <option value="CFP Francs - XPF">CFP Francs – XPF</option> -->
                <!-- <option value="Cyprus Pounds - CYP">Cyprus Pounds – CYP</option> -->
                <!-- <option value="Deutsche (Germany) Marks - DEM">Deutsche (Germany) Marks – DEM</OPTION> -->
                <!-- <option value="Dutch (Netherlands) Guilders - NLG">Dutch (Netherlands) Guilders – NLG</OPTION> -->
                <option value="Eastern Caribbean Dollars - XCD">Eastern Caribbean Dollars – XCD</option>
                <option value="Egypt Pounds - EGP">Egypt Pounds – EGP</option>
                <option value="Estonia Krooni - EEK">Estonia Krooni – EEK</option>
                <option value="Fiji Dollars - FJD">Fiji Dollars – FJD</option>
                <!-- <option value="Finland Markkaa - FIM">Finland Markkaa – FIM</OPTION> -->
                <!-- <option value="Germany Deutsche Marks - DEM">Germany Deutsche Marks – DEM</OPTION> -->
                <!-- <option value="Gold Ounces - XAU">Gold Ounces – XAU</option> -->
                <!-- <option value="Greece Drachmae - GRD">Greece Drachmae – GRD</OPTION> -->
                <option value="Guatemalan Quetzal - GTQ">Guatemalan Quetzal – GTQ</OPTION>
                <!-- <option value="Holland (Netherlands) Guilders - NLG">Holland (Netherlands) Guilders – NLG</OPTION> -->
                <option value="Iceland Kronur - ISK">Iceland Kronur – ISK</option>
                <!-- <option value="IMF Special Drawing Right - XDR">IMF Special Drawing Right – XDR</option> -->
                <!-- <option value="Iran Rials - IRR">Iran Rials – IRR</option> -->
                <!-- <option value="Iraq Dinars - IQD">Iraq Dinars – IQD</option> -->
                <!-- <option value="Ireland Pounds - IEP*">Ireland Pounds – IEP*</OPTION> -->
                <!-- <option value="Italy Lire - ITL*">Italy Lire – ITL*</OPTION> -->
                <option value="Jamaica Dollars - JMD">Jamaica Dollars – JMD</option>
                <option value="Jordan Dinars - JOD">Jordan Dinars – JOD</option>
                <option value="Ksh - KES">Kenya Shillings – KES</option>
                <option value="Korea (South) Won - KRW">Korea (South) Won – KRW</option>
                <option value="Kuwait Dinars - KWD">Kuwait Dinars – KWD</option>
                <option value="Lebanon Pounds - LBP">Lebanon Pounds – LBP</option>
                <!-- <option value="Luxembourg Francs - LUF">Luxembourg Francs – LUF</OPTION> -->
                <!-- <option value="Malta Liri - MTL">Malta Liri – MTL</option> -->
                <option value="Mauritius Rupees - MUR">Mauritius Rupees – MUR</option>
                <!-- <option value="Netherlands Guilders - NLG">Netherlands Guilders – NLG</OPTION> -->
                <option value="Oman Rials - OMR">Oman Rials – OMR</option>
               <!--  <option value="Palladium Ounces - XPD">Palladium Ounces – XPD</option> -->
                <!-- <option value="Platinum Ounces - XPT">Platinum Ounces – XPT</option> -->
                <!-- <option value="Portugal Escudos - PTE">Portugal Escudos – PTE</OPTION> -->
                <option value="Qatar Riyals - QAR">Qatar Riyals – QAR</option>
                <option value="lei - RON">Romania New Lei – RON</option>
                <!-- <option value="Romania Lei - ROL">Romania Lei – ROL</option> -->
                <option value="Saudi Arabia Riyals - SAR">Saudi Arabia Riyals – SAR</option>
                <!-- <option value="Silver Ounces - XAG">Silver Ounces – XAG</option> -->
                <!-- <option value="Slovakia Koruny - SKK">Slovakia Koruny – SKK</option> -->
                <!-- <option value="Slovenia Tolars - SIT">Slovenia Tolars – SIT</option>
                <option value="Spain Pesetas - ESP">Spain Pesetas – ESP</OPTION> -->
                <!-- <option value="Special Drawing Rights (IMF) - XDR">Special Drawing Rights (IMF) – XDR</option> -->
                <!-- <option value="Sudan Dinars - SDD">Sudan Dinars – SDD</option> -->
                <option value="Taiwan New Dollars - TWD">Taiwan New Dollars – TWD</option>
                <option value="Trinidad and Tobago Dollars - TTD">Trinidad and Tobago Dollars – TTD</option>
                <option value="Tunisia Dinars - TND">Tunisia Dinars – TND</option>
                <!-- <option value="Venezuela Bolivares - VEB">Venezuela Bolivares – VEB</option> -->
                <!-- <option value="Zambia Kwacha - ZMK">Zambia Kwacha – ZMK</option> -->
            </select>
                */  
            ?>

            <select  class="form-control" name="currency" required>
                <option value="<?php echo e($sitesettings->currencySymbol); ?> - <?php echo e($sitesettings->currencyCode); ?>" selected><?php echo e($sitesettings->currencySymbol); ?> - <?php echo e($sitesettings->currencyCode); ?></option>
                <option value="">Select Currency</option>
                <option value="$-Australian Dollar-AUD">Australian Dollar - AUD</option>
                <option value="R$-Brazilian Rea-BRL">Brazilian Rea - BRL</option>
                <option value="C$-Canadian Dollar-CAD">Canadian Dollar - CAD</option>
                <option value="Kč-Czech Koruna-CZK">Czech Koruna - CZK</option>
                <option value="kr.-Danish Krone-DKK">Danish Krone - DKK</option>
                <option value="€-Euro-EUR">Euro - EUR</option>
                <option value="HK$-Hong Kong Dollar-HKD">Hong Kong Dollar - HKD</option>
                <option value="Ft-Hungarian Forint-HUF">Hungarian Forint - HUF</option>
                <option value="₪-Israeli New Sheqel-ILS">Israeli New Sheqel - ILS</option>
                <option value="¥-Japanese Yen-JPY">Japanese Yen - JPY</option>
                <option value="RM-Malaysian Ringgit-MYR">Malaysian Ringgit - MYR</option>
                <option value="Mex$-Mexican Peso-MXN">Mexican Peso - MXN</option>
                <option value="kr-Norwegian Krone-NOK">Norwegian Krone - NOK</option>
                <option value="$-New Zealand Dollar-NZD">New Zealand Dollar - NZD</option>
                <option value="₱-Philippine Peso-PHP">Philippine Peso - PHP</option>
                <option value="zł-Polish Zloty-PLN">Polish Zloty - PLN</option>
                <option value="£-Pound Sterling-GBP">Pound Sterling - GBP</option>
                <option value="руб-Russian Ruble-RUB">Russian Ruble - RUB</option>
                <option value="S$-Singapore Dollar-SGD">Singapore Dollar - SGD</option>
                <option value="kr-Swedish Krona-SEK">Swedish Krona - SEK</option>
                <option value="CHF-Swiss Franc-CHF">Swiss Franc - CHF</option>
                <option value="NT$-Taiwan New Dolla-TWD">Taiwan New Dolla - TWD</option>
                <option value="฿-Thai Baht-THB">Thai Baht - THB</option>
                <option value="も-Turkish Lira-TRY">Turkish Lira - TRY</option>
                <option value="$-U.S. Dollar-USD">U.S. Dollar - USD</option>
            </select>
        </div>
    </div>
</div><?php /**PATH /var/www/html/resources/views/admin/settings/currency.blade.php ENDPATH**/ ?>